Searchable orgs
StoDevX/AAO-React-Native pull request #1073
Opened 2017-05-14 16:50 UTC by drewvolz

This adds the searchbar and searching capabilities to Student Orgs for iOS.

2017-05-14 17:56 UTC, hawkrives requested changes
Wow! Thanks!

2017-05-14 17:56 UTC, hawkrives commented on source/views/components/html-view.js
> +    style?: Object,
`number | Object | Array<number | Object>` pleases 😁

2017-05-14 17:56 UTC, hawkrives commented on source/views/student-orgs/detail.ios.js
> +import {HtmlView} from '../components/html-view'
Thanks!

2017-05-14 17:56 UTC, hawkrives commented on source/views/student-orgs/list.js
> +    results: {[key: string]: Array<StudentOrgType>},
`StudentOrgType[]`, please, for consistency with the line above.

2017-05-14 17:56 UTC, hawkrives commented on source/views/student-orgs/list.js
> +  splitToArray = (str: string) => {
At some point (not this PR!) we should really pull this out into its own function.

And, like, make some documentation of those functions.

2017-05-14 18:51 UTC, drewvolz commented on source/views/student-orgs/list.js
> +  splitToArray = (str: string) => {
Agreed.

2017-05-16 12:02 UTC, drewvolz commented
I would consider this PR as acceptable unless there are further changes anyone would like made.

2017-05-16 12:03 UTC, hawkrives approved these changes
Sure, let's merge it into my branch.

2017-05-16 12:03 UTC, merged