Format the header in hours reporting
StoDevX/AAO-React-Native pull request #1220
Opened 2017-06-17 20:18 UTC by drewvolz

This throws a few styles on the header for the building hours report view. I've also nixed the footer on the submit button.

A piece of #1158

Before | After
--|--
<img width="375" alt="unformatted" src="https://user-images.githubusercontent.com/5240843/27256036-9903c368-5378-11e7-9818-1b2bb82ce8c9.png"> | <img width="373" alt="formatted" src="https://user-images.githubusercontent.com/5240843/27256035-98fcd9ae-5378-11e7-8a2a-12f04fe0b795.png">

2017-06-17 21:28 UTC, hawkrives requested changes

2017-06-17 21:28 UTC, hawkrives commented on source/views/building-hours/report/overview.js
> +    borderColor: '#ebebeb',
This is in colors somewhere.

2017-06-17 21:28 UTC, hawkrives commented on source/views/building-hours/report/overview.js
> +          <Section>
Why?

2017-06-17 21:29 UTC, drewvolz commented on source/views/building-hours/report/overview.js
> +    borderColor: '#ebebeb',
It's not.

2017-06-17 21:29 UTC, drewvolz commented on source/views/building-hours/report/overview.js
> +          <Section>
It looked out of place.

2017-06-17 22:25 UTC, drewvolz commented on source/views/building-hours/report/overview.js
> +          <Section>
If you'd prefer it back in, I'll add it.

2017-06-17 22:34 UTC, hawkrives commented on source/views/building-hours/report/overview.js
> +          <Section>
I would like it for now, at least. I do want to rethink our buttons in this view, though, but that's a matter for a different PR.

2017-06-18 00:08 UTC, hawkrives approved these changes

2017-06-18 00:53 UTC, merged