Today widget view skeleton
StoDevX/AAO-React-Native pull request #1266
Opened 2017-07-07 02:49 UTC by drewvolz

This PR adds a "today extension" widget (the mini apps on iOS' lock screen). We are aiming to display SIS balances for Ole, Flex, and Print/Copy balances in the widget.

This puts the necessary skeleton in place to read from a JSON file, parse out the saved keys/values, and render them to the extension. It needs tweaking and polishing on the data-side as well as the view-side. This is a skeleton to be built upon.

No data | Data
--|--
![screen shot 2017-07-06 at 10 49 05 pm](https://user-images.githubusercontent.com/5240843/27941182-566f2f86-629d-11e7-856a-d497f00aa3ac.png) | ![screen shot 2017-07-06 at 10 48 29 pm](https://user-images.githubusercontent.com/5240843/27941184-56979aac-629d-11e7-9336-c3b268678c31.png)

2017-07-07 02:59 UTC, hawkrives requested changes
Wow! Nice proof of concept!

2017-07-07 02:59 UTC, hawkrives commented on ios/All About Olaf Widget/TodayViewController.m
> +  return [NSJSONSerialization JSONObjectWithData:data options:kNilOptions error:nil];
Shouldn't we handle the error here? So we don't, like, crash the widget?

2017-07-07 02:59 UTC, hawkrives commented on ios/AllAboutOlaf/All About Olaf.entitlements
> +		<string>$(AppIdentifierPrefix)NFMTHAZVS9.com.drewvolz.stolaf</string>
Do you know if you can use the bundle identifier function thing here?

2017-07-07 02:59 UTC, hawkrives commented on ios/AllAboutOlafWidget.entitlements
> +		<string>$(AppIdentifierPrefix)NFMTHAZVS9.com.drewvolz.stolaf.widget</string>
Also here (bundle identifier widget thing)

2017-07-07 02:59 UTC, hawkrives commented on ios/All About Olaf Widget/Base.lproj/MainInterface.storyboard
> +                                <rect key="frame" x="110" y="0.0" width="1" height="74"/>
Should these widths be a decimal? I know StyleSheet.hairlineWidth is fractional on retina screens. Don't know about storyboards.

2017-07-07 03:16 UTC, drewvolz commented on ios/All About Olaf Widget/Base.lproj/MainInterface.storyboard
> +                                <rect key="frame" x="110" y="0.0" width="1" height="74"/>
I have no idea. I'll have to look into it...

2017-07-07 03:16 UTC, drewvolz commented on ios/AllAboutOlaf/All About Olaf.entitlements
> +		<string>$(AppIdentifierPrefix)NFMTHAZVS9.com.drewvolz.stolaf</string>
Let me look into that...

2017-07-07 03:16 UTC, drewvolz commented on ios/AllAboutOlafWidget.entitlements
> +		<string>$(AppIdentifierPrefix)NFMTHAZVS9.com.drewvolz.stolaf.widget</string>
" "

2017-07-07 03:20 UTC, drewvolz commented on ios/AllAboutOlafWidget/TodayViewController.m
> +- (void)widgetPerformUpdateWithCompletionHandler:(void (^)(NCUpdateResult))completionHandler
Not sure if we need to make use of this if we're always strictly reading from a dumped file.

2017-07-07 03:20 UTC, drewvolz commented on ios/AllAboutOlafWidget/TodayViewController.m
> +    // [self testCreateFileAndData];
Uncomment this to create the test json file

2017-07-07 03:21 UTC, drewvolz commented on ios/AllAboutOlafWidget/TodayViewController.m
> +  // [self deleteSavedFile];
Uncomment this (and comment out  the creation below) to remove the test data.

2017-07-07 03:24 UTC, drewvolz commented
For whatever reason, I'm seeing this message when running the widget. Not sure if it is new, but I think it's tied to the widget?

> [App] if we're in the real pre-commit handler we can't actually add any new fences due to CA restriction

Anyways, [you can deal with it](https://stackoverflow.com/questions/38458170/ios-10-app-if-were-in-the-real-pre-commit-handler-we-cant-actually-add-any/40160779#40160779) by editing your Debug Run scheme with an environment variable.

2017-07-07 04:51 UTC, elijahverdoorn commented
Guess this means I should put finishing touches on the Android Home Screen stuff... I'll get to it... Review of this one coming soon, too burnt tonight to do it justice; thanks for the work @drewvolz.

2017-07-09 02:10 UTC, elijahverdoorn approved these changes
Other than what @hawkrives requested, I'm good with this.

2017-07-09 18:00 UTC, drewvolz commented on ios/All About Olaf Widget/TodayViewController.m
> +  return [NSJSONSerialization JSONObjectWithData:data options:kNilOptions error:nil];
Decent idea.

2017-07-14 19:31 UTC, hawkrives commented on ios/AllAboutOlaf/All About Olaf.entitlements
> +		<string>$(AppIdentifierPrefix)NFMTHAZVS9.com.drewvolz.stolaf</string>
Have you found anything about this?

2017-07-14 19:34 UTC, hawkrives requested changes

2017-07-14 19:34 UTC, hawkrives commented on ios/AllAboutOlaf.xcodeproj/project.pbxproj
> +			path = "AllAboutOlafWidget";
If you do "stuff" with Xcode, it will remove this line. Please do stuff with xcode until it removes this.

2017-07-14 19:34 UTC, hawkrives commented on ios/AllAboutOlaf.xcodeproj/project.pbxproj
> +				IPHONEOS_DEPLOYMENT_TARGET = 10.3;
Is the rest of the app targeting 10.3 or 8.4?

2017-07-14 19:34 UTC, hawkrives commented on ios/AllAboutOlafWidget/Base.lproj/MainInterface.storyboard
> +                                <rect key="frame" x="224" y="0.0" width="82" height="48"/>
I'd like for you to look into auto-layout and figure out if these fixed-position lines move appropriately. 

We want to handle different widget sizes nicely, namely the 5/6/6+ sizes, as well as whatever an iPad uses.

2017-07-14 19:40 UTC, drewvolz commented on ios/AllAboutOlafWidget/Base.lproj/MainInterface.storyboard
> +                                <rect key="frame" x="224" y="0.0" width="82" height="48"/>
Still working on learning auto-layout. I will investigate this...

2017-07-14 19:42 UTC, drewvolz commented on ios/AllAboutOlaf.xcodeproj/project.pbxproj
> +			path = "AllAboutOlafWidget";
Can you explain that again, please?

2017-07-14 19:43 UTC, drewvolz commented on ios/AllAboutOlaf.xcodeproj/project.pbxproj
> +				IPHONEOS_DEPLOYMENT_TARGET = 10.3;
Hard to say. Cursory glance at `master` .pbxproj shows 8.1 referenced three times and 10.1 referenced two times. I'll look closer later.

2017-07-14 22:25 UTC, hawkrives commented
Regenerating the merge commit after #1286.

2017-09-02 21:37 UTC, drewvolz commented
Putting this on hold.

2017-09-02 21:37 UTC, closed without merging