News image changes
StoDevX/AAO-React-Native pull request #1426
Opened 2017-08-14 22:47 UTC by drewvolz

These two commits change the News views.

- Aligns images to left side of view
- Rounds the image thumbnail corners
- Uses a placeholder for blank images
- Adds logos for the placeholders

Politicole | Oleville | KSTO
--|--|--
<img width="370" alt="politicole" src="https://user-images.githubusercontent.com/5240843/29295132-cc5dc774-8120-11e7-9337-fef61c1257cf.png">| <img width="371" alt="oleville" src="https://user-images.githubusercontent.com/5240843/29295133-cc6a841e-8120-11e7-9431-d535b50f34a7.png"> | <img width="374" alt="ksto" src="https://user-images.githubusercontent.com/5240843/29295134-cc6bc360-8120-11e7-96b5-9b9cf4764a26.png">

2017-08-15 01:00 UTC, hawkrives requested changes
Overall, 👍!

- … can we get the new thumbnails to be all the same size?

2017-08-15 01:00 UTC, hawkrives commented on source/views/news/news-list.js
> +    <NewsRow onPress={this.onPressNews} story={item} blank={this.props.thumb} />
Why is this new prop called `blank`? Please change it to `thumb` or `thumbnail`.

2017-08-15 01:00 UTC, hawkrives commented on source/views/news/news-row.js
> +    borderRadius: 5,
:+1: on the `borderRadius`

2017-08-15 01:00 UTC, hawkrives commented on source/views/news/news-container.js
> +    thumb: number,
<abbr title="bikeshed time">🚲 🏠 ⌚️</abbr>   – `thumb` or `thumbnail`?

2017-08-15 01:16 UTC, drewvolz commented on source/views/news/news-container.js
> +    thumb: number,
If you'd prefer thumbnail, that's fine.

2017-08-17 23:39 UTC, drewvolz commented
> can we get the new thumbnails to be all the same size?

@hawkrives I've resized the circular images to all be 90x90. As far as the stolaf logo... I've resized it to be 77x90. I do not want to turn a more naturally rectangular shape into a squashed square.

Okay? I think I've satisfied the rest of your requests!

2017-08-18 13:04 UTC, hawkrives approved these changes

2017-08-18 13:04 UTC, hawkrives commented
I just want to see if me poking Danger was enough to fix it.

2017-08-18 13:51 UTC, drewvolz commented
Danger is still having a bad day.

2017-08-18 16:27 UTC, hawkrives commented
We'll merge it anyway; it's probably just something with this particular message.

Would you mind making an issue, assigning it to me, and linking to the danger comment, please, so I can look into it later?

2017-08-18 16:33 UTC, merged