Handle blank contacts in org listings
StoDevX/AAO-React-Native pull request #1427
Opened 2017-08-14 23:47 UTC by drewvolz

This PR fixes issues in:

- **iOS**: the contact info for a Student Org member was completely blank if no first/last name.
- **Android**: the contact info for a Student Org member contained extra whitespace if no first/last name.

Closes #1388 

~ | Before | After |
-- | -- | -- |
iOS | ![truth-blank](https://user-images.githubusercontent.com/5240843/29296534-e7331fec-8128-11e7-9c06-068fdef2a2f1.png) | <img width="374" alt="truth-filled" src="https://user-images.githubusercontent.com/5240843/29296533-e730f1cc-8128-11e7-9d28-870c572e61bd.png">
Android | ![android-truth-blank](https://user-images.githubusercontent.com/5240843/29296535-ead53c3e-8128-11e7-8b0b-28eac39c9a9d.png) | ![android-truth-filled](https://user-images.githubusercontent.com/5240843/29296536-ead90490-8128-11e7-9b7b-8a8b7d2bb245.png)

2017-08-15 00:55 UTC, hawkrives requested changes
- Please extract this helper function into the helper file. If there is no helper file here, please create one.
- When you extract the function, please change it to accept one parameter, as follows: `(c: ContactPersonType)`. That is, remove the object-as-first-parameter dance.

2017-08-15 01:00 UTC, drewvolz commented
> Please extract this helper function into the helper file. If there is no helper file here, please create one.

[`clean-org.js`](https://github.com/StoDevX/AAO-React-Native/blob/master/source/views/student-orgs/clean-org.js) exists but I don't think it would belong in there... do you? I think it might warrant another helper file.

2017-08-15 01:02 UTC, hawkrives commented
@drewvolz Instead of making another file, I might just rename `clean-org.js` to `util.js` or something, and add the helper function in there.

Since `clean-org.js` has only one function already.

2017-08-18 00:05 UTC, drewvolz commented
I think this is ready to go.

2017-08-18 01:41 UTC, hawkrives requested changes

2017-08-18 01:41 UTC, hawkrives commented on source/views/student-orgs/detail.android.js
> +import {showNameOrEmail} from './util'
Please import both of these at once.

2017-08-18 01:41 UTC, hawkrives commented on source/views/student-orgs/detail.ios.js
> +import {showNameOrEmail} from './util'
Please import both of these at once.

2017-08-18 01:41 UTC, hawkrives commented
One last thing! It looks good!

2017-08-18 01:47 UTC, drewvolz commented
Why don't we import from `types` like that?

2017-08-18 12:47 UTC, hawkrives commented
@drewvolz you mean here?

```js
import type {StudentOrgType} from './types'
import type {TopLevelViewPropsType} from '../types'
```

Because they're importing from two different files.

If you see anywhere where there are two import statements targeting the same file, please merge them into one :)

2017-08-18 13:49 UTC, drewvolz commented
Good catch. I’ve now merged the import statements you mentioned earlier.

2017-08-18 16:26 UTC, hawkrives approved these changes

2017-08-18 16:29 UTC, merged