Important contacts refresh
StoDevX/AAO-React-Native pull request #1469
Opened 2017-08-26 18:14 UTC by drewvolz

This PR introduces a refresh to the important contacts view.

* Simplified list/detail views
* Group contacts by category

~ | List | Detail
--|--|--
iOS | ![ios-list](https://user-images.githubusercontent.com/5240843/29743929-a110f41e-8a68-11e7-8c4a-203ef0fa6e91.png) | ![ios-detail](https://user-images.githubusercontent.com/5240843/29743931-a1415604-8a68-11e7-8fd7-03b3792831a5.png)
Android | ![android-list](https://user-images.githubusercontent.com/5240843/29743942-b04a5bbe-8a68-11e7-9df5-c7427e7109a8.png) | ![android-detail](https://user-images.githubusercontent.com/5240843/29743943-b04b2b8e-8a68-11e7-882a-7a4adbae0131.png)

2017-08-26 18:42 UTC, drewvolz commented
What am I missing... `npm run validate-data -- --quiet` shows that "category" is an additional prop.

2017-08-27 01:26 UTC, hawkrives requested changes
Overall, nice work! Really nice!

2017-08-27 01:26 UTC, hawkrives commented on source/views/contacts/contact-list.js
> +  renderFooter = () =>
Please extract this into a constant outside of the class - it doesn't need to be called as a function. 

Just assign the ListFooter to a constant called "footer" or something. It should be in this file, as it's similar in intent to the styles object.

2017-08-27 01:26 UTC, hawkrives commented on source/views/contacts/contact-list.js
> +  const grouped = groupBy(contacts, b => b.category || 'Other')
We don't need the `||` here, as we're guaranteed through the schema that our objects will have a category.

2017-08-27 01:26 UTC, hawkrives commented on source/views/contacts/contact-list.js
> + * iOS Contact page
Remove the word iOS?

2017-08-27 02:07 UTC, drewvolz commented
Changes addressed. Now to wait on the build again.

2017-08-27 02:27 UTC, hawkrives approved these changes

2017-08-27 04:21 UTC, merged