We're unofficial (so let's tell the world so)
StoDevX/AAO-React-Native pull request #2419
Opened 2018-03-10 06:36 UTC by hawkrives

Partially tongue-in-cheek, but I do think that we need something like this.

Wording of messages, layout, and behavior (currently there is none) is all open to discussion.

<img src="https://user-images.githubusercontent.com/464441/37239105-ecbb6d96-23fa-11e8-9631-d118adfe0de7.png" width=320>

2018-03-10 06:39 UTC, drewvolz commented
As always, I’ll be the Debbie Downer. I’d like to request the wording to change.

2018-03-10 07:07 UTC, hawkrives commented
That's perfectly fine, but I'm going to come back at'cha with a request for suggestions ;-)

2018-03-10 16:39 UTC, drewvolz commented
- An unofficial St. Olaf app
- For students, by students
- For Oles, by Oles
- Not supported by St. Olaf

2018-03-10 22:00 UTC, hannesmcman submitted a review, later dismissed

2018-03-11 02:12 UTC, drewvolz requested changes

2018-03-11 02:12 UTC, drewvolz commented on source/views/home/notice.js
> +	'☃️',
Do we really want this

2018-03-11 02:12 UTC, drewvolz commented on source/views/home/notice.js
> +	'we are (not) olaf',
This one doesn't tell me much

2018-03-11 02:12 UTC, drewvolz commented on source/views/home/notice.js
> +	'SGA-owned and misunderstood',
Not necessarily true

2018-03-11 02:12 UTC, drewvolz commented on source/views/home/notice.js
> +	'I AM AN UNOFFICIAL APP',
Not a fan of the use of "I" here

2018-03-11 02:15 UTC, drewvolz commented
What we say on the front of the app is very important to me. This is what is forward facing and what the user will be confronted with _every single time they use the app_, and what new users will first read. I'd rather be generic than confusing. I'd like the messages to be straightforward, which is why I suggested what I said in this message https://github.com/StoDevX/AAO-React-Native/pull/2419#issuecomment-372043402.

2018-03-14 03:13 UTC, drewvolz approved these changes
👍 :shipit:

2018-03-14 03:37 UTC, merged