Greenkeeper/prettier 1.12.1
StoDevX/AAO-React-Native pull request #2550
Opened 2018-04-24 20:05 UTC by drewvolz

Closes #2521

2018-04-24 20:28 UTC, hawkrives requested changes
Rebase onto `master` and then apply the prettier changes, please

2018-04-26 03:39 UTC, rye submitted a review, later dismissed

2018-04-26 03:46 UTC, rye submitted a review, later dismissed

2018-04-26 03:47 UTC, rye approved these changes

2018-04-26 03:47 UTC, hawkrives approved these changes

2018-04-26 12:32 UTC, merged