Add Push Notifications Capability
StoDevX/AAO-React-Native pull request #2566
Opened 2018-05-02 15:40 UTC by hannesmcman

This PR is aimed at configuring the app to allow us to send remote push notifications to users using OneSignal. It may also include configuring local notifications using `react-native-push-notifications` if we want it to.

2018-05-02 16:38 UTC, hawkrives commented
(For the flow types, just mark them as `: any` for now.)

2018-05-02 17:29 UTC, hawkrives submitted a review, later dismissed
A bunch of little tweaks to the native project files

2018-05-02 17:29 UTC, hawkrives commented on android/app/build.gradle
> +    compile project(':react-native-onesignal')
Sort this

2018-05-02 17:29 UTC, hawkrives commented on android/app/src/main/java/com/allaboutolaf/MainApplication.java
> +import com.geektime.rnonesignalandroid.ReactNativeOneSignalPackage;
Sort this

2018-05-02 17:29 UTC, hawkrives commented on android/app/src/main/java/com/allaboutolaf/MainApplication.java
> +            new ReactNativeOneSignalPackage(),
Sort and reindent this

2018-05-02 17:29 UTC, hawkrives commented on android/settings.gradle
> +project(':react-native-onesignal').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-onesignal/android')
Sort these

2018-05-02 17:29 UTC, hawkrives commented on ios/AllAboutOlaf.xcodeproj/project.pbxproj
> +					"\"$(SRCROOT)/$(TARGET_NAME)\"",
Remove dup

2018-05-02 17:29 UTC, hawkrives commented on ios/AllAboutOlaf.xcodeproj/project.pbxproj
> +					"\"$(SRCROOT)/$(TARGET_NAME)\"",
Remove dup

2018-05-02 17:29 UTC, hawkrives commented on ios/AllAboutOlaf/AppDelegate.m
> +
Remove extra line

2018-05-02 17:29 UTC, hawkrives commented on ios/AllAboutOlaf/Info.plist
> +	<string>We only use your location when you would expect us to, and never when you aren't using the app.</string>
Undo

2018-05-02 17:29 UTC, hawkrives commented on ios/AllAboutOlaf/Info.plist
> +	<string>We only use your location when you would expect us to, and never when you aren't using the app.</string>
Undo

2018-05-02 19:18 UTC, hawkrives requested changes
I don't think I have any more nitpicky comments after this.

2018-05-02 19:18 UTC, hawkrives commented on android/app/build.gradle
> +    compile project(':react-native-onesignal')
Change this to `implementation`

2018-05-02 19:18 UTC, hawkrives commented on ios/AllAboutOlaf/AppDelegate.m
> +                                                    appId:@"a46c6f2f-a240-4908-a359-801911e9b9ea"];
Align the `:` here, please.

```objc
self.oneSignal = [[RCTOneSignal alloc] initWithLaunchOptions:launchOptions
                                                       appId:@"a46c6f2f-a240-4908-a359-801911e9b9ea"];
```

2018-05-02 19:18 UTC, hawkrives commented
@hannesmcman Did you get the extension signed?

2018-05-02 19:20 UTC, hannesmcman commented
@hawkrives No, I think I still need you to configure that..that's why I put the `don'tmerge` label on this

2018-05-02 19:44 UTC, hawkrives submitted a review, later dismissed

2018-05-02 19:44 UTC, hawkrives commented
@hannesmcman Alright. I'll try to do that some time this week/end.

2018-05-03 15:43 UTC, hannesmcman commented
@hawkrives Let me know when you think you've got that figured out, because we'll still need to add the extension to this PR before we merge.

2018-05-03 15:50 UTC, hawkrives commented
Could you add the extension to this PR so the build can fail, so I'll know when I've got it working?

2018-05-03 19:19 UTC, hannesmcman commented
@rye Can you test this on your android phone and make sure it works there?

2018-05-03 19:22 UTC, rye commented
@hannesmcman sure, I'll add it to my to-do list for tonight.

2018-05-28 22:16 UTC, hannesmcman commented
@hawkrives Is this still on your radar?

2018-08-03 00:41 UTC, hawkrives commented
Okay, so we need a cert to sign the extension? @hannesmcman please bug me on Sunday if you haven't heard anything else by then. I'll try to do this this weekend.

2018-08-03 01:06 UTC, hannesmcman commented
@hawkrives Yep! Will do!

2018-08-04 22:42 UTC, drewvolz commented
@hannesmcman you mentioned this in a [comment](https://github.com/StoDevX/AAO-React-Native/pull/2566#issuecomment-386340552) above:

> we'll still need to add the extension to this PR before we merge.

Do you remember the context of the keyword _this_? Are you referring to adding the `OneSignalNotificationServiceExtension` to this PR?

2018-08-04 23:01 UTC, drewvolz commented on source/app.js
> +		startStatusBarColorChanger()
Where is the start/stop coming from? Currently it breaks things.

2018-08-04 23:03 UTC, drewvolz commented on source/app.js
> +		startStatusBarColorChanger()
I feel like it might be related to the way we were telling the iOS status bar to be dark or light? @hawkrives

2018-08-05 00:04 UTC, hawkrives commented
The last merge from master seems to have broken things.

2018-08-06 01:33 UTC, hannesmcman commented
@drewvolz That was before I added the extension. Then I added it, which broke the build because of the lack of a proper cert.

2018-08-06 02:27 UTC, hawkrives commented
@drewvolz this branch should run again (js-wise) as of edd0cb7

2018-08-08 07:52 UTC, hannesmcman commented
@hawkrives how’s the cert coming? :)

2018-08-08 12:57 UTC, drewvolz commented
Hawken tried to pass that off to me, and I was trying to get a sense of what actually needed to be done. I haven’t been able to figure it out yet, either.

2018-08-10 16:33 UTC, hannesmcman commented
We need to add a provisioning profile to the OneSignal Extension. Not sure if it can be the same as for the app itself.

2018-08-12 20:02 UTC, drewvolz commented
something something

* OneSignal's tool to generate the provisioning file https://onesignal.com/provisionator
* Steps https://documentation.onesignal.com/v5.0/docs/generate-an-ios-push-certificate#section-1-provisioning

2018-08-13 15:54 UTC, hannesmcman commented
@hawkrives I think your the only admin on the Apple developer account right? I think you're the only one able to use the tool Drew linked in the comment above...

2018-08-13 15:56 UTC, hawkrives commented
Drew is also an admin

2018-08-13 15:57 UTC, hannesmcman commented
@hawkrives @drewvolz Well then I guess you two will just have to arm wrestle!

2018-08-13 16:47 UTC, drewvolz commented
@hawkrives I don't have the permissions to generate a cert on your account. I only have access to certs/identifiers/profiles from my personal developer account.

2018-08-13 17:25 UTC, hawkrives commented
@drewvolz noted

2018-08-16 03:45 UTC, hawkrives approved these changes
sure

2018-08-16 04:10 UTC, merged