Update KSTO logo
StoDevX/AAO-React-Native pull request #2739
Opened 2018-08-05 19:08 UTC by drewvolz

Personally prefer the older image. This PR serves as a discussion.

Before | After
--|--
<img width="433" alt="old" src="https://user-images.githubusercontent.com/5240843/43688989-88a835c0-98b0-11e8-836c-03dd9e71677e.png"> | <img width="433" alt="new" src="https://user-images.githubusercontent.com/5240843/43688988-88897c0c-98b0-11e8-8f60-a6351a0a8d28.png">

2018-08-05 20:22 UTC, rye commented
Is this a change that was made upstream (i.e. by KSTO)?

2018-08-05 20:47 UTC, hawkrives commented
Remove the outline

2018-08-05 21:34 UTC, drewvolz commented
@rye it’s an upstream change, but we don’t have to adopt it.

2018-08-05 22:10 UTC, hawkrives commented
@drewvolz where did you even find that logo?

2018-08-05 23:44 UTC, drewvolz commented
Looks like you found it... that's the one.

2018-08-05 23:56 UTC, hawkrives commented
Could you please:

- Remove the blue border
- Resize the image file to remove the transparent edges

Currently, there's no easy way to change the button color for the radio view; I'll take that on in a separate PR.

2018-08-06 00:18 UTC, drewvolz commented
Updated the image to reflect that there is no border now.

2018-08-06 00:19 UTC, hawkrives requested changes

2018-08-06 00:19 UTC, hawkrives commented on source/views/streaming/radio/controller.js
> +					const borderStyle = imageBorder ? styles.logoBorder : null
Inline this variable into the `logo` array, please. You can also shorten it by `imageBorder && styles.logoBorder`.

2018-08-06 00:37 UTC, hawkrives approved these changes

2018-08-06 01:10 UTC, hawkrives submitted a review, later dismissed
Please remove the commit with the original image and force-push.

2018-08-06 02:12 UTC, rye submitted a review, later dismissed

2018-08-06 02:17 UTC, hawkrives submitted a review, later dismissed
Could you split adding the image and the code changes into two commits, please?

2018-08-06 02:21 UTC, hawkrives approved these changes

2018-08-06 02:37 UTC, merged