More padding to bottom of credits view
StoDevX/AAO-React-Native pull request #2817
Opened 2018-08-19 21:13 UTC by drewvolz

On smaller screens, the bottom of the credits view is cut off.

Before | After
--|--
<img width="408" alt="old-not-x" src="https://user-images.githubusercontent.com/5240843/44313247-300de500-a3c2-11e8-994f-cf03923e50dd.png"> | <img width="408" alt="new-not-x" src="https://user-images.githubusercontent.com/5240843/44313248-300de500-a3c2-11e8-9f78-d7d0b5d5b07e.png">
<img width="436" alt="old-x" src="https://user-images.githubusercontent.com/5240843/44313249-300de500-a3c2-11e8-84fd-0e010c9c0edb.png"> | <img width="436" alt="new-x" src="https://user-images.githubusercontent.com/5240843/44313250-300de500-a3c2-11e8-8420-b08e8d7accd3.png">

2018-08-19 21:13 UTC, drewvolz commented
@hawkrives I was unable to find a suitable way within Glamorous to adjust the bottom padding without an additional view. If you can think of one, I'd be happy to try it.

2018-08-19 21:14 UTC, drewvolz commented
The diff ignoring whitespace https://github.com/StoDevX/AAO-React-Native/pull/2817/files?w=1

2018-08-20 04:10 UTC, hannesmcman approved these changes

2018-08-20 04:13 UTC, rye approved these changes

2018-08-20 04:15 UTC, hawkrives requested changes
I want to dig into this and find the root cause, instead of papering over it with extra padding… I will attempt to do this as soon as possible.

2018-08-25 00:25 UTC, closed without merging