Fixed multiple settings menus from being summoned on the home screen
StoDevX/AAO-React-Native pull request #326
Opened 2016-11-15 05:39 UTC by drewvolz

This prevents the settings button from being mashed quickly which results in pushing two or more views to the stack. This closes #155.

2016-11-15 12:06 UTC, hawkrives submitted a review, later dismissed

2016-11-15 12:06 UTC, hawkrives commented on app.js
> +let settingsButtonActive = false
Make this a state variable in App, and pass it into the LeftButtom function as a prop.

2016-11-15 12:06 UTC, hawkrives commented on app.js
> +let settingsButtonActive = false
Along with a callback to a member function in App to toggle the variable.

2016-11-15 12:06 UTC, hawkrives commented on app.js
> +            settingsButtonActive = true
Then call that callback here

2016-11-15 12:06 UTC, hawkrives commented on app.js
> +          onPress={settingsButtonActive ? () => {} : () => {
You might also name the noop function, since we're naming the other.

2016-11-15 12:06 UTC, hawkrives commented on app.js
> +            settingsButtonActive = false
This online function should probably be extracted to a member function,`closeSettingsScreen` or something.

2016-11-15 23:31 UTC, drewvolz commented
From chatting with you, this sounds as if it will be a more complicated fix than we first imagined.

2016-11-16 17:52 UTC, hawkrives requested changes
Moar feedbacks

2016-11-16 17:52 UTC, hawkrives commented on app.js
> +          onPress={settingsButtonActive ? () => {} : () => {
Import `noop` from lodash and use it here, and move the `settingsButtonActive = true` line into the `openSettings` function.

`onPress={settingsButtonActive ? noop : () => openSettings(route, navigator)}`

2016-11-16 17:52 UTC, hawkrives commented on app.js
> +            settingsButtonActive = false
This is still a comment I'd like to have addressed.

2016-11-16 18:04 UTC, hawkrives commented on app.js
> +let settingsButtonActive = false
Ignore these

2016-11-16 18:04 UTC, hawkrives commented on app.js
> +          onPress={settingsButtonActive ? () => {} : () => {
Ignore this comment

2016-11-16 18:05 UTC, hawkrives commented on app.js
> +            settingsButtonActive = true
Ignore this comment

2016-11-16 18:56 UTC, hawkrives requested changes
Almost there

2016-11-16 18:56 UTC, hawkrives commented on app.js
> +  settingsButtonActive = false
Flip these?

2016-11-16 18:56 UTC, hawkrives commented on app.js
> +          onPress={settingsButtonActive ? noop : () => openSettings(route, navigator)}
✅

2016-11-16 18:56 UTC, hawkrives commented on app.js
>            }}
Almost

We need to give `navigator` to the function

`onPress={() => closeSettings(navigator)}`

2016-11-16 18:56 UTC, hawkrives commented on app.js
> +  settingsButtonActive = false
It also needs to accept `navigator` as a prop

2016-11-16 19:01 UTC, hawkrives commented on app.js
> +          onPress={() => {
put this on one line and remove the outer set of braces?

2016-11-16 19:02 UTC, hawkrives commented on app.js
> +  settingsButtonActive = false
and should we flip these two?

I don't think there'll be any functional difference

2016-11-16 19:02 UTC, drewvolz commented on app.js
> +          onPress={() => {
Sure

2016-11-16 19:02 UTC, drewvolz commented on app.js
> +  settingsButtonActive = false
Done.

2016-11-16 19:03 UTC, drewvolz commented on app.js
> +  settingsButtonActive = false
We could?

2016-11-16 19:14 UTC, hawkrives approved these changes

2016-11-16 19:14 UTC, merged