Meals remaining
StoDevX/AAO-React-Native pull request #335
Opened 2016-11-16 16:45 UTC by elijahverdoorn

Ok. I've got this working. The code's not beautiful, but it does work. I made a few decisions in there that we might want to discuss:

* Layout of settings
* Redirection to settings from SIS
* Re-naming variables in the SIS

I'd appreciate suggestions and tweaks.
(I'm especially not proud of the error checking code, there's got to be a better way to do that)

2016-11-16 16:45 UTC, elijahverdoorn commented
![screen shot 2016-11-16 at 10 45 28 am](https://cloud.githubusercontent.com/assets/12042702/20356331/d6e98172-abe9-11e6-9cbb-c720a626038c.png)

2016-11-16 16:53 UTC, zimmer18 commented on lib/financials.js
> +  return {flex, ole, print};
; ?

2016-11-16 17:00 UTC, hawkrives commented on lib/financials.js
> +  return {flex, ole, print};
Bad semicolon :)

2016-11-16 17:00 UTC, drewvolz commented on views/sis/balances.js
> +    console.log('TESTING')
:zap:

2016-11-16 17:00 UTC, drewvolz commented on lib/financials.js
> +    console.log("error in fetching meal data")
Maybe we should present an alert, or some information for the user to know that it could not be fetched?

2016-11-16 17:00 UTC, drewvolz commented on views/settings/index.js
>          console.log(err)
Maybe we could let the user know we could not log them out?

2016-11-16 17:03 UTC, drewvolz commented
Try running `npm run lint` to get past the CI failures in Travis and Appveyor.

2016-11-16 17:16 UTC, hawkrives requested changes

2016-11-16 17:16 UTC, hawkrives commented on lib/financials.js
> +    })
Please don't use `map` for side-effects; `map` should be a pure function, not mutating anything outside of its scope.

Instead, you could do 

```js
let values = data.map((item) => {
  return item.next.next.children[0].data
})
```

2016-11-16 17:16 UTC, hawkrives commented on lib/login.js
> +    return {false}
According to your type defs, this should be `return {result: false}`

2016-11-16 17:16 UTC, hawkrives commented on views/settings/index.js
>        console.log(res)
Remove this `log`

2016-11-16 17:16 UTC, hawkrives commented on views/settings/index.js
> +      username.replace('@stolaf.edu', '') // just in case someone uses their full email, throw the part we don't need away
Might as well just make this generic; remove anything after `@`? Something like `.replace(/@.*$/, '')`?

2016-11-16 17:16 UTC, hawkrives commented on views/settings/index.js
>            {actionCell}
I don't like having both of the login buttons right next to each other. Can we pull the "Sign In with Google" button into its own `<Section/>`?

2016-11-16 17:16 UTC, hawkrives commented on views/sis/balances.js
> +    console.log('TESTING')
Remove this `log`, please

2016-11-16 17:16 UTC, hawkrives commented on views/sis/balances.js
> +    dailyMeals: null|number,
Yay flow types!

2016-11-16 17:16 UTC, hawkrives commented on views/sis/balances.js
> +      data = await getWeeklyMealsRemaining()
Maybe don't reuse the variable? No harm, I suppose, but I dislike reusing variables in the same scope…

2016-11-16 17:16 UTC, hawkrives commented on views/sis/balances.js
> +              detail = {dailyMeals}
No spaces around the `=`

2016-11-16 17:16 UTC, hawkrives commented on views/sis/balances.js
> +              detail = {weeklyMeals}
No spaces around the `=`

2016-11-16 17:16 UTC, hawkrives commented on views/settings/index.js
> +        <Section header='LOGIN' footer='Note: This application requires logging in to Google and inputting your St. Olaf username and password in order use all features.'>
I feel like this should say `[…] requires both logging into Google and […]`, with a `both` in there somewhere?

2016-11-16 17:17 UTC, hawkrives commented
My biggest tweak suggestion would probably be that we could extract the St. Olaf login section into its own component – it displays the two fields and the button, and accepts an onLogin prop that it calls when the user pushes the button.

2016-11-16 17:17 UTC, hawkrives commented on lib/financials.js
> +    console.log("error in fetching meal data")
Nah. It'll just say N/A probably.

2016-11-16 17:24 UTC, drewvolz commented on lib/financials.js
> +    console.log("error in fetching meal data")
I really think being clear is important here. Otherwise, you get 1-star reviews on the store saying it does not work.

2016-11-16 17:28 UTC, hawkrives commented on lib/financials.js
> +    console.log("error in fetching meal data")
I'm just not sure what someone would expect. We have no idea what the failure cases would be, really, so we can't provide tailored error messages. The most common case will be that your password has changed, but that should be dealt with similarly to the SIS data, I think.

2016-11-16 17:34 UTC, drewvolz commented on views/settings/index.js
> +        <Section header='LOGIN' footer='Note: This application requires logging in to Google and inputting your St. Olaf username and password in order use all features.'>
"in order **to** use all features"

2016-11-16 17:42 UTC, drewvolz commented
Should we change the text on the login buttons? I will say that I have become fairly desensitized to most login forms, and multiple options either means register/login (not the case here), or login with EITHER of these methods. I feel that some might glide past our "note" below the buttons. This would lead to problems when they login with only one method... because we are asking for both.

I am proposing that we make this more clear. Can we list the buttons as: 

[**First**, Sign In to St. Olaf]
[**Next**, Sign In with Google]

2016-12-02 20:18 UTC, elijahverdoorn commented
I think I've addressed all the major issues with this one.

2016-12-02 20:22 UTC, hawkrives commented
I'll check the merge conflict locally

2016-12-02 20:22 UTC, elijahverdoorn commented
@hawkrives I was just doing that.

2016-12-02 20:27 UTC, hawkrives commented
@elijahverdoorn Try something for me: tap on the text "username" (the label for the username field)?

I'm afraid it might crash.

2016-12-02 20:31 UTC, hawkrives commented
More to the point, it's still calling the `focusUsername` and `focusPassword` functions that I wrote for the original login fields, but they don't exist anymore.

2016-12-02 20:31 UTC, hawkrives commented on views/settings/index.js
> +          onSubmitEditing={this.focusPassword}
`this.focusPassword` needs to be restored from the history

2016-12-02 20:32 UTC, hawkrives requested changes
These functions

2016-12-02 20:32 UTC, hawkrives commented on views/settings/index.js
> +        <Text onPress={this.focusUsername} style={styles.label}>Username</Text>
`this.focusUsername` needs to be restored from the history

2016-12-02 20:32 UTC, hawkrives commented on views/settings/index.js
> +        <Text onPress={this.focusPassword} style={styles.label}>Password</Text>
`this.focusPassword` needs to be restored from the history

2016-12-02 20:39 UTC, elijahverdoorn commented on views/settings/index.js
> +        <Text onPress={this.focusUsername} style={styles.label}>Username</Text>
Gotcha. I've run out of time for the moment, but I'll be back on it later. Good catch.

2016-12-02 20:50 UTC, hawkrives approved these changes

2016-12-02 21:30 UTC, hawkrives commented on views/settings/index.js
> +        <Text onPress={this.focusPassword} style={styles.label}>Password</Text>
done

2016-12-02 21:30 UTC, hawkrives commented on views/settings/index.js
> +        <Text onPress={this.focusUsername} style={styles.label}>Username</Text>
done

2016-12-02 21:32 UTC, hawkrives commented on views/settings/index.js
> +          onSubmitEditing={this.focusPassword}
done

2016-12-03 03:31 UTC, merged