apply two small circle config tweaks
StoDevX/AAO-React-Native pull request #3436
Opened 2019-01-27 02:18 UTC by hawkrives

I can't find a reference to `cmd` in the docs, but they do talk about `command`. If the build fails, we'll know not to do the change.

The other is just clarification; numbers will get stringified anyway during env insertion, so let's be consistent.

2019-01-27 02:48 UTC, drewvolz approved these changes

2019-01-27 15:12 UTC, rye requested changes

2019-01-27 15:12 UTC, rye commented on .circleci/config.yml
>      # cmd: key is passed to solve a weird issue (see GitHub PR's 2170 and 2173).
Comment string needs an update

2019-01-27 23:08 UTC, rye requested changes
Needs changelog, then good to go.

2019-01-31 16:59 UTC, rye approved these changes

2019-01-31 16:59 UTC, merged