Buildings Closing In Countdown
StoDevX/AAO-React-Native pull request #352
Opened 2016-11-22 17:45 UTC by mattk410

Added 'Closing In' countdown to buildings. Got the ListView to refresh automatically and on pull-down.

![Uploading Simulator Screen Shot Nov 21, 2016, 9.35.15 AM.png…]()

2016-11-22 18:15 UTC, hawkrives requested changes
Looking good! I'm chatting with you elsewhere about possible ways to avoid creating new dataSources every render, but I'm not going to block on that. It's not like we have a ton of items in this view.

2016-11-22 18:15 UTC, hawkrives commented on views/building-hours/format-building-hours.js
> +  if (openStatus === 'Almost Closed'){
Space between the ) and { please. I need to tell eslint to check that.

2016-11-22 18:15 UTC, hawkrives commented on views/building-hours/index.js
> +
Remove these blank lines please

2016-11-22 18:15 UTC, hawkrives commented on views/building-hours/index.js
> +      dataSource: this.getDataSource(),
Please move the rest of the object to individual lines, like you did with `dataSource`.

2016-11-22 18:29 UTC, hawkrives commented
After doing some more research, I found http://stackoverflow.com/questions/34715217/what-are-the-exact-inputs-to-rowhaschanged-in-listview-datasource, which says that `rowHasChanged` is applied at dataSource creation time, not render time. Which makes sense.

So I withdraw any objections to the recreation of the dataSource.

My other three requests will stand, though 😸 

Good work, @mattk410!

2016-11-22 20:51 UTC, drewvolz commented on views/building-hours/index.js
> +      dataSource: this.getDataSource(),
✅

2016-11-22 20:51 UTC, drewvolz commented on views/building-hours/index.js
> +
✅

2016-11-22 20:51 UTC, drewvolz commented on views/building-hours/format-building-hours.js
> +  if (openStatus === 'Almost Closed'){
✅

2016-11-22 21:03 UTC, hawkrives approved these changes
:shipit:

2016-11-22 21:03 UTC, merged

2016-11-23 06:08 UTC, drewvolz commented on views/building-hours/format-building-hours.js
> +    return `Closing in ${closingIn} minutes`
I commented on this in #358. I believe when it will show "1 minutes" at some point. We should fix that.