Fix android tabbar crashing
StoDevX/AAO-React-Native pull request #3875
Opened 2019-07-20 20:56 UTC by drewvolz

Use first readable color (string) instead of returned object

2019-07-20 21:13 UTC, drewvolz reviewed
⚠️ This isn't correct yet, working on it...

2019-07-20 21:49 UTC, drewvolz commented
✅ This is correct!

2019-07-20 22:23 UTC, rye approved these changes
Sounds good to me!

2019-07-21 01:44 UTC, hawkrives requested changes
`toString()` is documented to return differently formatted values depending on the input – can we switch to `toHexString()` (or another format) so we can be sure what we're getting out?

I think RN can handle any of the string formats, but I'd like consistency :-)

2019-07-21 01:46 UTC, drewvolz commented
Okay. I opted to be consistent with the existing codebase which uses `toString()` for the tinycolor calls, but I'm happy to change it.

2019-07-21 02:11 UTC, hawkrives commented
After talking with Drew, who's testing this PR, we've opted to switch to `toRgbString()` everywhere, as we have some semi-transparent colors which can be handled by toRgbString but not toHexString.

2019-07-21 02:17 UTC, drewvolz commented
After looking closer, my message about being consistent doesn't make sense. There are existing parts of the codebase that do use `toRgbString()` which is what we want! So yep, we're changing to that for everything.

2019-07-21 03:32 UTC, hawkrives approved these changes

2019-07-21 03:32 UTC, merged