Small tweaks
StoDevX/AAO-React-Native pull request #416
Opened 2016-12-06 21:19 UTC by hawkrives

This PR is made up of two changes:
- reduce font weight of ios navbar
- darken app tint color

We have been using a heavier font weight (`700`, or `bold`) in our navbar since … well, since always. That's because my brain said that 600 == bold, not 700, but iOS uses 600 for navbars, not 700.

And secondly, the app's tint color is too light IMHO. This changes it to the same color used for tinting the app in other places, most noticeably the iOS tab bars. This makes it much easier to read the titlebar, especially when night shift is enabled, IMO.

![diff-1](https://cloud.githubusercontent.com/assets/464441/20943951/38784a9e-bbc7-11e6-93d3-ca4956cf24ad.gif)

| Before | After |
|:---:|:---:|
![before](https://cloud.githubusercontent.com/assets/464441/20943949/377813f4-bbc7-11e6-9fa3-e3cd901ef3ea.png) | ![after](https://cloud.githubusercontent.com/assets/464441/20943950/37869a96-bbc7-11e6-81f7-f4f96a8ace36.png)

---

Comment period: until someone from Olaf comments.

2016-12-06 22:08 UTC, drewvolz commented
@hawkrives I know it might be a challenge, but would you be able to photograph what you consider difficult to read with your nightshift enabled? I know screenshotting will not work for this task.

I believe it may be hard to read on your particular device with a certain tint of nightshift, but I am not completely convinced that it is warranted to adjust the tint to be darker if it is readable on other settings of nightshift.

Lastly, I believe your tint change is only relevant on one platform... someone would have to apply a blue-light filter to an android device?

How does everyone else in @StoDevX/all-about-olaf else feel about these changes? I personally am a fan of the previous `olevilleGold` color, as it was extracted from St. Olaf's website, but if it really is beneficial, I could be persuaded.

2016-12-07 14:56 UTC, drewvolz approved these changes
I have had a change of mind. It is just a color, and if @hawkrives has a preference and would like to change it, that is fine by me.

2016-12-08 22:15 UTC, hawkrives commented
Hawken would like to change it.

If anyone wants to _not_ change it, then I'll remove that change.

2016-12-10 02:13 UTC, elijahverdoorn requested changes

2016-12-10 02:13 UTC, elijahverdoorn commented on app.js
> +    backgroundColor: c.tint,
What if we change it to `c.olevilleGold`? It's a bit darker, but not as dark as the `tint`

2016-12-10 14:26 UTC, drewvolz commented on app.js
> +    backgroundColor: c.tint,
The proposal is to change it to a darker color named tint away from OlevilleGold. It is more orange than gold. For context, [here is the PR ](https://github.com/StoDevX/AAO-React-Native/pull/416).

2016-12-10 19:51 UTC, elijahverdoorn commented on app.js
> +    backgroundColor: c.tint,
Wow I'm blind. Thanks @drewvolz. I think I'd like to keep in the same color family as `olevilleGold`, but if we want to go with a darker variation that's ok. Maybe one of these:
* `#C28F00`
* `#987000`

@hawkrives what do you think of those?

2016-12-12 19:55 UTC, hawkrives commented on app.js
> +    backgroundColor: c.tint,
`#C28F00` | `#987000`
---|---
<img width="45" alt="987000" src="https://cloud.githubusercontent.com/assets/464441/21114371/80d6f588-c072-11e6-80ef-38e6cfe5275e.png"> | <img width="45" alt="c28f00" src="https://cloud.githubusercontent.com/assets/464441/21114372/80d9a06c-c072-11e6-9c40-e2fb57068efb.png">

2016-12-15 17:07 UTC, hawkrives commented
Hawken is dropping the color change part of this PR.

2016-12-15 20:57 UTC, merged