change a bunch of descriptions in the Pause menu
StoDevX/AAO-React-Native pull request #458
Opened 2016-12-28 18:04 UTC by hawkrives

Also we should make a `menus` label

2016-12-29 18:46 UTC, drewvolz requested changes

2016-12-29 18:46 UTC, drewvolz commented on docs/menus/pause.json
> +      "note": "Includes a cup of Marinara, Ranch, BBQ, or Honey Mustard sauce"
This is the note for Chicken Strips. Perhaps we do not need a note here.

2016-12-29 18:46 UTC, drewvolz commented on docs/menus/pause.json
> +      "description": "Pizza built on pita bread; includes two toppings",
I do not think "specialty" items include an "extra two toppings". We need to check with a kitchen manager or worker to be sure.

2016-12-29 18:49 UTC, drewvolz commented on docs/menus/pause.json
> +      "note": "Includes a cup of Marinara, Ranch, BBQ, or Honey Mustard sauce"
On another note, large orders are a pain-point for the pause. We could use the note here to communicate "For orders of 4 or more pizzas, visit Oleville"

2016-12-29 20:35 UTC, hawkrives commented on docs/menus/pause.json
> +      "note": "Includes a cup of Marinara, Ranch, BBQ, or Honey Mustard sauce"
Can do

2016-12-29 20:36 UTC, hawkrives commented
@drewvolz I addressed your comments.

(I need to merge this soon, so my stationMenus stuff can be tested before I submit the filters PR)

2016-12-30 03:39 UTC, drewvolz approved these changes

2016-12-30 03:41 UTC, merged