Thumbnails on news stories
StoDevX/AAO-React-Native pull request #463
Opened 2016-12-31 03:40 UTC by drewvolz

This adds 50x50 thumbnails to stories with images embedded into their content. It seeks out the first image within the story content and uses it as the image's source. Stories without images will display as they did previously.

Screenshots:

Thumbnails | No thumbnails
---|---
 ![oleville-news](https://cloud.githubusercontent.com/assets/5240843/21575623/91aee2cc-cee0-11e6-95a6-25d972d44e8d.png) |  ![st-olaf-news](https://cloud.githubusercontent.com/assets/5240843/21575622/91aee114-cee0-11e6-83bd-f7dd8cca540a.png)

2016-12-31 04:44 UTC, hawkrives requested changes

2016-12-31 04:44 UTC, hawkrives commented on views/news/news-container.js
> +    return false
Generally, an optional react component is denoted with `null` for the no-component case, not `false`. Please switch this to use `null`.

2016-12-31 04:44 UTC, hawkrives commented on views/news/news-container.js
> +    if (imageMatch !== null && imageMatch !== undefined) {
Just do `if (imageMatch)`?

2016-12-31 18:39 UTC, drewvolz commented on views/news/news-container.js
> +    if (imageMatch !== null && imageMatch !== undefined) {
Good point, thanks.

2016-12-31 18:39 UTC, drewvolz commented on views/news/news-container.js
> +    return false
Done.

2017-01-01 06:09 UTC, hawkrives reviewed
- [x] I would like to request a screenshot of a list with a mix of both thumbnailed and non-thumbnailed stories. 

- [x] Furthermore, since most of these run on Wordpress, what happens when the image to be thumbnailed is smaller than the thumbnail?

- [x] What about when it's the "N comments" image that Wordpress sticks at the end of posts in an RSS feed sometimes?

I just want to make sure we've got the edge cases here.

2017-01-04 04:59 UTC, drewvolz commented
> I would like to request a screenshot of a list with a mix of both thumbnailed and non-thumbnailed stories.

<img width="407" alt="randomized" src="https://cloud.githubusercontent.com/assets/5240843/21631063/0c8811d6-d205-11e6-810f-cdd40124c996.png">

> Furthermore, since most of these run on Wordpress, what happens when the image to be thumbnailed is smaller than the thumbnail?

We won't show an image for it. I have adjusted to check the image height and width based upon reading your question.

> What about when it's the "N comments" image that Wordpress sticks at the end of posts in an RSS feed sometimes?

We are now making sure that icons are at least 50x50, so I doubt they would show up. If it is that large, we will display it. But I doubt it will be there.

2017-01-04 14:52 UTC, hawkrives requested changes

2017-01-04 14:52 UTC, hawkrives commented on views/news/news-container.js
> +    return icon
This won't work correctly. `Image.getSize` is asynchronous – the callback may not (should not, I think) have executed by the time we return from the function.

We'll have to make `findImage` return a promise, instead, I think, and store some state in the component.

2017-01-04 14:52 UTC, hawkrives commented
Thanks for the investigation and comments. It's coming along nicely!

2017-01-04 22:41 UTC, elijahverdoorn commented
I like where this is going!

2017-01-06 06:41 UTC, drewvolz commented
@hawkrives added functionality to check the image sizes asynchronously. Looks like we're good to go.

2017-01-06 06:47 UTC, drewvolz commented
We may need to wrap image fetching with the global fetch. I am noticing errors occasionally.

<img width="417" alt="screen shot 2017-01-06 at 1 45 35 am" src="https://cloud.githubusercontent.com/assets/5240843/21709817/072e6574-d3b2-11e6-84b1-74d8756881eb.png">

2017-01-06 13:36 UTC, hawkrives requested changes

2017-01-06 13:36 UTC, hawkrives commented on views/news/news-container.js
> +        return null
You should resolve() here too. You never want to `return` from the body of a Promise constructor.

2017-01-06 13:36 UTC, hawkrives commented on views/news/news-container.js
> +
Nit: extra blank line.

2017-01-06 13:36 UTC, hawkrives commented on views/news/news-container.js
> +class NewsRow extends React.Component {
I would like to pull this component into its own file. News-item-Row.js

2017-01-06 15:18 UTC, drewvolz commented on views/news/news-container.js
> +        return null
Resolving here caused a problem where null was being returned somewhere down below

2017-01-06 15:18 UTC, drewvolz commented on views/news/news-container.js
> +class NewsRow extends React.Component {
Great idea

2017-01-06 15:23 UTC, hawkrives commented on views/news/news-container.js
> +        return null
I'm struggling to understand that, since we do the `if (!thumbnailUrl)` which should catch any falsy values including `null`.

2017-01-08 21:06 UTC, drewvolz commented on views/news/news-container.js
> +        return null
Manitou Messenger error if I have `resolve(null)` on line 51

<img width="407" alt="screen shot 2017-01-08 at 4 05 27 pm" src="https://cloud.githubusercontent.com/assets/5240843/21753481/4bfba16a-d5bc-11e6-9608-9d23a195138a.png">

2017-01-08 21:18 UTC, drewvolz commented on views/news/news-container.js
> +        return null
What about a `return` after the `resolve(null`? It seems to behave well.

      if (!url) {
        resolve(null)
        return
      }

2017-01-08 21:20 UTC, hawkrives commented on views/news/news-container.js
> +        return null
That tells us that this is a timing issue

2017-01-08 21:20 UTC, hawkrives commented on views/news/news-container.js
> +        return null
That tells us that this is a timing issue

2017-01-08 21:20 UTC, hawkrives commented on views/news/news-container.js
> +        return null
That tells us that this is a timing issue

2017-01-08 21:22 UTC, hawkrives commented on views/news/news-container.js
> +        return null
Because, if nothing else, our check in render should prevent us from rendering the image with "null" as the source.

2017-01-09 16:09 UTC, hawkrives commented
My current feelings on this:

http://stackoverflow.com/questions/31651610/return-value-of-promises-resolve-reject-functions

The return value of a new Promise is ignored. That brings me back to, there's an underlying timing bug somewhere, which is being exposed by resolving.

And until we resolve that bug I'm uncomfortable merging it. 

Because, if nothing else, our check in `render` ought to not render the Image of the URL is null, and that's obviously not working for some reason.

I want to know why that's not working.

On the bright side, at least it's reproducible and not intermittent. 😄

2017-02-14 15:47 UTC, hawkrives commented
Closed in favor of #693

2017-02-14 15:47 UTC, closed without merging