<FaqView/>
StoDevX/AAO-React-Native pull request #476
Opened 2017-01-03 16:57 UTC by hawkrives

> Don't merge; this depends on the data changes in #475.

Adds an FAQ view to load the FAQs as hosted on Github Pages.

That way they're as easy to update as merging a PR.

2017-01-03 17:34 UTC, drewvolz requested changes

2017-01-03 17:34 UTC, drewvolz commented on views/faqs/index.js
> +  url = "https://stodevx.github.io/AAO-React-Native/faqs.json"
Will this link work after your data reorg? Current is a 404.

2017-01-03 17:34 UTC, drewvolz commented on docs/faqs.json
> +  "text": "<style>\nbody {\n  -webkit-overflow-scrolling: touch;\n  font-family: -apple-system, Roboto, sans-serif;\n  background-color: transparent;\n}\nh1 {\n  font-size: 1.35em;\n}\n</style>\n\n<h
Do we need to specify webkit, font-family, and background color, and font size in `faqs.json` as well as in `faqs.md`?

2017-01-03 17:34 UTC, drewvolz commented on data/faqs.md
> +  -webkit-overflow-scrolling: touch;
This is also specified in `faqs.json` ?

2017-01-03 17:41 UTC, hawkrives commented on data/faqs.md
> +  -webkit-overflow-scrolling: touch;
`faqs.json` is the generated version of `faqs.md`. It contains the processed text from faqs.md.

2017-01-03 17:42 UTC, hawkrives commented on views/faqs/index.js
> +  url = "https://stodevx.github.io/AAO-React-Native/faqs.json"
Yes. The entire contents of the `docs/` folder on master is published at `https://stodevx.github.io/AAO-React-Native/`.

2017-01-03 17:42 UTC, hawkrives commented on docs/faqs.json
> +  "text": "<style>\nbody {\n  -webkit-overflow-scrolling: touch;\n  font-family: -apple-system, Roboto, sans-serif;\n  background-color: transparent;\n}\nh1 {\n  font-size: 1.35em;\n}\n</style>\n\n<h
Halfway. We should never need to manually edit the file in `docs/`; instead, it's generated from the associated file(s) in `data/`.

2017-01-03 17:46 UTC, drewvolz approved these changes

2017-01-04 22:31 UTC, elijahverdoorn approved these changes

2017-01-04 23:04 UTC, merged