Fix buttons again again
StoDevX/AAO-React-Native pull request #492
Opened 2017-01-05 06:03 UTC by drewvolz

Two issues are tackled here here:

(1) Blank views can be pushed on a corrupted stack
  * Happens on **settings** button mashing
  * Happens on **edit** button mashing

(2) Multiple views can be pushed to the navigator stack
  * I can touch either the settings or edit buttons sequentially and very quickly to make this happen.
  * It will render both views, as both were pushed individually in sequential order.... we do not check for that yet.

<hr>

Solution for (1) is to check outside of the called function whether the function should be called instead of within the function.

    let onPressEditHome = (settingsButtonActive || editHomeButtonActive) ? null : openEditHome(route, navigator)
    let onPressSettings = (settingsButtonActive || editHomeButtonActive) ? null : openSettings(route, navigator)

Solution for (2) is to check if the opposite navbar button is active in addition to itself. This is a little iffy, which I would like feedback on. The onDismiss is being called for the `HomeView` and changing their values when the `HomeView` disappears instead of when the `EditHomeView` or `SettingsView` views disappear. The logic works the same, but maybe there is a more elegant solution.

     if (editHomeButtonActive || settingsButtonActive)

Closes #155

2017-01-05 06:55 UTC, hawkrives requested changes
Nitpick as I can't think atm: instead of providing "null" as a callback function, please use "() => {}", aka an empty lambda

2017-01-06 06:38 UTC, drewvolz commented
The empty lambdas are now provided as callbacks. Thank you for your feedback.

2017-01-08 21:00 UTC, drewvolz commented
Any other requests?

2017-01-08 21:13 UTC, hawkrives commented
I _see_ the changes, but I don't _grok_ the changes. 

I guess I was waiting until I understood why they were needed. 

If you can't reproduce with these, then Ok.

2017-01-08 21:26 UTC, drewvolz commented
I believe this fixes the issues listed.

2017-01-26 01:02 UTC, drewvolz commented
What about utilizing redux to store the state we're manipulating and checking a bunch of times?

2017-01-26 01:03 UTC, hawkrives commented
That's gotta be slower than just checking a local variable though, yeah?

2017-02-12 03:10 UTC, closed without merging