Hook-up student orgs list and detail views
StoDevX/AAO-React-Native pull request #5976
Opened 2022-04-23 05:55 UTC by drewvolz

* Convert to functional components
* Set up navigation title and back props

2022-04-23 06:14 UTC, hawkrives commented
Don't forget a "make files" in the root of the repo!

2022-04-23 07:38 UTC, drewvolz commented
Ah, thanks. Maybe I should add that as a hook locally.

2022-04-23 14:25 UTC, hawkrives commented
@drewvolz I pushed the regenerated error files

2022-04-23 14:27 UTC, hawkrives requested changes
maybe tweak these names to make it clear they're platform-dependent?

2022-04-23 14:27 UTC, hawkrives commented on source/views/student-orgs/detail.ts
> +	NavigationOptions as ListNavigationOptions,
```suggestion
	NavigationOptions as IosDetailNavigationOptions,
```

maybe?

2022-04-23 14:27 UTC, hawkrives commented on source/views/student-orgs/detail.ts
> +	NavigationOptions as DetailNavigationOptions,
```suggestion
	NavigationOptions as AndroidDetailNavigationOptions,
```

2022-04-23 14:27 UTC, hawkrives commented on source/views/student-orgs/detail.ts
> +	Platform.OS === 'ios' ? ListNavigationOptions : DetailNavigationOptions
```suggestion
	Platform.OS === 'ios' ? IosDetailNavigationOptions : AndroidDetailNavigationOptions
```

2022-04-23 19:33 UTC, hawkrives commented
LGTM! What do you think about tweaking the names in that one file?

2022-04-23 19:43 UTC, drewvolz commented
Oh no. I made that change but it's not here. Where did that commit go...

2022-04-23 20:53 UTC, hawkrives approved these changes

2022-04-24 00:02 UTC, rye approved these changes

2022-04-24 00:15 UTC, merged