more view (part 2): ccc-ified
StoDevX/AAO-React-Native pull request #6206
Opened 2022-07-03 04:39 UTC by drewvolz

- follow-up to #6175 
- add schema and definition yaml to generate a-to-z json
- utilize the caching server to proxy a new `/a-to-z` endpoint (exists on PR branch)

2022-07-08 17:08 UTC, hawkrives requested changes

2022-07-08 17:08 UTC, hawkrives commented on source/init/data.ts
> +		url: '/a-to-z',
Doesn't this need an `API()` call?

2022-07-08 17:08 UTC, hawkrives commented on source/views/more/index.tsx
> +	let groupedOriginal = React.useMemo(() => data, [data])
Can we remove this line entirely?

2022-07-08 17:12 UTC, drewvolz commented on source/init/data.ts
> +		url: '/a-to-z',
Did I forget that? I guess I forgot that!

2022-07-08 17:13 UTC, drewvolz commented on source/views/more/index.tsx
> +	let groupedOriginal = React.useMemo(() => data, [data])
I suppose we could!

2022-07-10 03:23 UTC, hawkrives approved these changes

2022-07-10 03:25 UTC, merged