codepush integration
StoDevX/AAO-React-Native pull request #692
Opened 2017-02-12 00:17 UTC by drewvolz

**CodePush** is a cloud service that enables developers to deploy mobile app updates directly to their users' devices. It works by acting as a central repository that developers can publish updates to (JS, HTML, CSS and images), and that apps can query for updates from.

This allows you to have a more deterministic and direct engagement model with your user base, when addressing bugs and/or adding small features that don't require you to re-build a binary and re-distribute it through the respective app stores.

It is immaculately documented and provides an outstanding command line tool to help you release an update, rollback to a previous release, or one of the numerous tasks it allows.

We are going to hit the ground running with 3 lanes/deployments: `nightly`, `staging`, and `release`. We will be able to alpha test, beta test, limited release test, and fully release features with these configurations.

With limited releases, we are able to release features in to the wild on a given percentage of devices. If we are rolling out a new feature but want to be sure we don't witness a lot of new crashes, we can slowly roll something out to 20% of the users, or 50% ... etc. What we roll out in a `nightly` beta could be promoted to the `staging` beta and then introduced into the `release` version.

A lot can happen with CodePush. For the most part, it enables us to add features and updates _instantly_. No waiting for the app store approval process and no need to wait for users to download a new binary. This is free, this is smart, and this is going to change the way we develop and push features.

<hr>

- [Background information on Microsoft CodePush](https://github.com/microsoft/code-push)
- [How to use CodePush thru the command line](https://github.com/Microsoft/code-push/blob/master/cli/README.md)

<img width="756" alt="2e7df77c-37bb-11e6-9456-e392af7f7b84" src="https://cloud.githubusercontent.com/assets/5240843/22858501/9671b450-f08d-11e6-9528-bbb63fbc78e2.png">

2017-02-12 00:27 UTC, hawkrives requested changes
Nitpicks

2017-02-12 00:27 UTC, hawkrives commented on package.json
> +      "nightly": "cMzHZZ5aUuk0ILftVFFwJvZLxiycEJN_nzUOz"}
Please move the closing } to the next line

2017-02-12 00:27 UTC, hawkrives commented on ios/AllAboutOlaf/AppDelegate.m
>    // see https://github.com/Microsoft/react-native-code-push/issues/393
Do we need this comment anymore?

2017-02-12 00:27 UTC, hawkrives commented on android/settings.gradle
> +project(':react-native-code-push').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-code-push/android/app')
Please alphabetize these below.

2017-02-12 00:27 UTC, hawkrives commented on android/app/src/main/java/com/allaboutolaf/MainApplication.java
> +            new CodePush(getResources().getString(R.string.reactNativeCodePush_androidDeploymentKey), getApplicationContext(), BuildConfig.DEBUG),
Please alphabetize this and move it down and unindent it.

2017-02-12 00:27 UTC, hawkrives commented on android/app/src/main/java/com/allaboutolaf/MainApplication.java
> +
Please remove this blank line.

2017-02-12 00:27 UTC, hawkrives commented on android/app/src/main/java/com/allaboutolaf/MainApplication.java
> +import com.microsoft.codepush.react.CodePush;
Please alphabetize this section. (select the whole chunk; push f5 in sublime)

2017-02-12 00:27 UTC, hawkrives commented on android/app/build.gradle
> +    compile project(':react-native-code-push')
Please alphabetize this and move it down.

2017-02-12 00:36 UTC, drewvolz commented on ios/AllAboutOlaf/AppDelegate.m
>    // see https://github.com/Microsoft/react-native-code-push/issues/393
probably not 👍

2017-02-12 00:39 UTC, hawkrives commented
Overall, I'm really excited for CodePush!

2017-02-12 01:21 UTC, drewvolz commented
ready to be rebased!

2017-02-12 02:58 UTC, hawkrives approved these changes

2017-02-12 03:10 UTC, hawkrives commented
@drewvolz you should probably check to make sure this all works as intended now that I've rebased it.

2017-02-13 08:04 UTC, drewvolz commented
@hawkrives confirmed, I've now tested again a deployment to the release versions of iOS and Android.

2017-02-13 23:02 UTC, hawkrives commented
@elijahverdoorn There's not a lot to this, but I'd like you to sign off on this before merge.

2017-02-18 18:56 UTC, hawkrives commented
Ignore the dependency-ci failure; we disabled it again.

2017-02-18 19:48 UTC, drewvolz commented
@elijahverdoorn this is ready for your review.

2017-02-19 04:34 UTC, hawkrives commented
For instance, my meals stuff today could have been pushed out through CodePush, or the News thumbnails stuff that's awaiting review.

2017-02-19 19:08 UTC, merged