Feature new student orgs
StoDevX/AAO-React-Native pull request #816
Opened 2017-03-06 07:19 UTC by drewvolz

This creates a grouping for new student organizations to be featured at the top of the orgs list.

<img width="400" alt="new orgs" src="https://cloud.githubusercontent.com/assets/5240843/23600064/b6cac71e-0212-11e7-86d3-dcd0241148b8.png">

2017-03-06 13:22 UTC, hawkrives requested changes
One requested change, and one comment: would you look into AlphabetListView and see if you can specify the letters on the right side separately?  IIRC, you can specify an "extractor" function which will produce the items used for the side; you could do `$groupableName === "New" ? "•" : $groupableName[0]` or something to change "New" into a single char.

2017-03-06 13:22 UTC, hawkrives commented on source/views/student-orgs/list.js
> +      let newOrgsSortableNames = map(newOrgs, item => {
Join this into one statement, if you would?

sorted
  .filter()
  .map()

2017-03-06 15:42 UTC, drewvolz commented
I will look into how to specify groupnames explicitly.

2017-03-06 15:53 UTC, hawkrives commented
We could probably call it "• New" and leave it how it's currently taking the first letter of each item, if we wanted.

2017-03-06 15:55 UTC, hawkrives commented
Given https://github.com/sunnylqm/react-native-alphabetlistview#getsectiontitle, I think that the `getSectionTitle` prop is the the ListSectionHeader, and `getSectionListTitle` is for the things on the right.

2017-03-07 02:41 UTC, drewvolz commented
Done! Thanks for your help.

2017-03-07 04:16 UTC, hawkrives requested changes
You have cellHeight in here twice, accidentally.

2017-03-07 04:40 UTC, hawkrives requested changes

2017-03-07 04:40 UTC, hawkrives commented on source/views/student-orgs/list.js
> +        getSectionListTitle={this.getSectionListTitle}
Please move this line above the comment

2017-03-07 04:40 UTC, hawkrives commented on source/views/student-orgs/list.js
> +  getSectionListTitle = (...args: any) => {
`= (name: string) =>` and get rid of the array access

2017-03-07 04:40 UTC, hawkrives commented on source/views/student-orgs/list.js
> +      let combined = {...newOrgsGrouped, ...grouped}
Please inline this into the setState call (setState({orgs: {...newOrgs, ...allOrgs}})

2017-03-07 04:40 UTC, hawkrives commented on source/views/student-orgs/list.js
>        let grouped = groupBy(sorted, '$groupableName')
Please rename this to allOrgsGrouped

2017-03-07 04:40 UTC, hawkrives commented on source/views/student-orgs/list.js
> +        }
Could you just put this whole thing on one line please? return through the end bracket.

2017-03-07 15:32 UTC, hawkrives commented
Can you please merge master into this branch and run prettier on it?

2017-03-07 15:44 UTC, hawkrives commented
So the current implementation goes like this:

```js
// All orgs
let sorted = sortBy(withSortableNames, '$sortableName')
let allOrgsGrouped = groupBy(sorted, '$groupableName')
// New orgs
let newOrgs = sorted.filter(org => org.newOrg).map(item => {
  return {...item, $groupableName: 'New'}
})
let newOrgsGrouped = groupBy(newOrgs, '$groupableName')
let combined = {...newOrgsGrouped, ...allOrgsGrouped}
this.setState({orgs: combined})
```

What about changing it to this?

```js
let sorted = sortBy(withSortableNames, '$sortableName')
let allOrgsGrouped = groupBy(sorted, '$groupableName')

let newOrgs = sorted.filter(org => org.newOrg)
let orgs = {New: newOrgs, ...allOrgsGrouped}

this.setState({orgs: orgs})
```

2017-03-07 16:04 UTC, hawkrives approved these changes

2017-03-07 19:12 UTC, merged

2017-03-08 05:12 UTC, drewvolz commented
That particular redesign resulted in every org being marked as new. Also, the font size for that new icon has decreased.

2017-03-08 16:55 UTC, hawkrives commented
I think you commented on the wrong PR?

2017-03-08 19:03 UTC, drewvolz commented
I meant to comment here as I thought this PR had something to do with it... although it was introduced in [#830 Add new warnings to linter](https://github.com/StoDevX/AAO-React-Native/pull/830)